@extends('layouts.app')
@section('title', 'Bitácora')
@section('content')
<div class="mb-4"><h1 class="h3 mb-1">Bitácora de actividad</h1><p class="text-body-secondary mb-0">Consulta quién hizo cada cambio en el inventario y encuentra un evento sin descargar archivos.</p></div>

<form method="GET" action="{{ route('audit-logs.index') }}" class="card mb-4"><div class="card-body"><div class="row g-3"><div class="col-lg-3"><label class="form-label" for="q">Buscar</label><input id="q" type="search" name="q" value="{{ request('q') }}" class="form-control" placeholder="Activo, producto, motivo…"></div><div class="col-lg-2"><label class="form-label" for="desde-filtro">Desde</label><input id="desde-filtro" type="date" name="desde" value="{{ request('desde') }}" class="form-control"></div><div class="col-lg-2"><label class="form-label" for="hasta-filtro">Hasta</label><input id="hasta-filtro" type="date" name="hasta" value="{{ request('hasta') }}" class="form-control"></div><div class="col-lg-2"><label class="form-label" for="usuario">Usuario</label><select id="usuario" name="usuario" class="form-select"><option value="">Todos</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) request('usuario') === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div><div class="col-lg-1"><label class="form-label" for="accion">Acción</label><select id="accion" name="accion" class="form-select"><option value="">Todas</option>@foreach($actions as $action)<option value="{{ $action }}" @selected(request('accion') === $action)>{{ ucfirst($action) }}</option>@endforeach</select></div><div class="col-lg-2"><label class="form-label" for="entidad">Elemento</label><select id="entidad" name="entidad" class="form-select"><option value="">Todos</option>@foreach($entities as $entity)<option value="{{ $entity }}" @selected(request('entidad') === $entity)>{{ ucfirst(str_replace('_', ' ', $entity)) }}</option>@endforeach</select></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Filtrar</button><a class="btn btn-outline-secondary" href="{{ route('audit-logs.index') }}">Limpiar filtros</a></div></div></div></form>

<div class="d-flex align-items-center justify-content-between mb-2"><h2 class="h5 mb-0">Eventos recientes</h2><span class="text-body-secondary small">{{ $entries->total() }} registro(s)</span></div><div class="card mb-4"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Elemento</th><th>Motivo / detalle</th><th>Resultado</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td class="text-nowrap">{{ \Illuminate\Support\Carbon::parse($entry->creado_at)->timezone(config('app.timezone'))->format('d-m-Y H:i') }}</td><td>{{ $entry->usuario_nombre ?? 'Sistema' }}@if($entry->usuario_username)<div class="small text-body-secondary">{{ $entry->usuario_username }}</div>@endif</td><td><span class="badge text-bg-primary">{{ ucfirst($entry->accion) }}</span></td><td>{{ ucfirst(str_replace('_', ' ', $entry->entidad_tipo)) }}@if($entry->entidad_id)<div class="small text-body-secondary">#{{ $entry->entidad_id }}</div>@endif</td><td class="text-break">{{ $entry->motivo ?: 'Sin detalle registrado' }}</td><td><span class="badge {{ $entry->resultado === 'exitoso' ? 'text-bg-success' : 'text-bg-danger' }}">{{ ucfirst($entry->resultado) }}</span></td></tr>@empty<tr><td colspan="6" class="text-center text-body-secondary p-4">No hay eventos que coincidan con los filtros.</td></tr>@endforelse</tbody></table></div></div><div class="mb-5">{{ $entries->links() }}</div>

<div class="d-flex align-items-center justify-content-between mb-2"><h2 class="h5 mb-0">Generar archivo de bitácora</h2><span class="small text-body-secondary">Para respaldos o revisiones externas</span></div><form method="POST" action="{{ route('audit-logs.generate') }}" class="card mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label" for="desde">Desde</label><input id="desde" type="date" name="desde" value="{{ old('desde', now()->startOfMonth()->toDateString()) }}" class="form-control" required>@error('desde')<div class="text-danger small">{{ $message }}</div>@enderror</div><div class="col-md-4"><label class="form-label" for="hasta">Hasta</label><input id="hasta" type="date" name="hasta" value="{{ old('hasta', now()->toDateString()) }}" class="form-control" required>@error('hasta')<div class="text-danger small">{{ $message }}</div>@enderror</div><div class="col-md-2"><label class="form-label" for="formato">Formato</label><select id="formato" name="formato" class="form-select"><option value="csv" @selected(old('formato', 'csv') === 'csv')>CSV (recomendado)</option><option value="pdf" @selected(old('formato') === 'pdf')>PDF</option></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-outline-primary w-100"><i class="bi bi-file-earmark-arrow-down me-1"></i>Generar</button></div></div></div></form>

<h2 class="h5">Archivos generados</h2><div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Período UTC</th><th>Archivo</th><th>Integridad SHA-256</th><th>Generada</th><th></th></tr></thead><tbody>@forelse($archives as $archive)<tr><td>{{ \Illuminate\Support\Carbon::parse($archive->periodo_desde)->format('d-m-Y H:i') }} — {{ \Illuminate\Support\Carbon::parse($archive->periodo_hasta)->format('d-m-Y H:i') }}</td><td>{{ basename($archive->ruta) }}</td><td><code>{{ $archive->sha256 }}</code></td><td>{{ \Illuminate\Support\Carbon::parse($archive->creado_at)->format('d-m-Y H:i') }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('audit-logs.download', $archive->id) }}"><i class="bi bi-download me-1"></i>Descargar</a></td></tr>@empty<tr><td colspan="5" class="text-center text-body-secondary p-4">Aún no se han generado bitácoras.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $archives->links() }}</div>
@endsection
