@extends('layouts.app')
@section('title', 'Inventario físico')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h3 mb-1">Inventario físico</h1><p class="text-body-secondary mb-0">Revisa una ubicación escaneando los códigos de los activos que encuentres.</p></div></div>

<form method="POST" action="{{ route('physical-inventories.store') }}" class="card mb-4">@csrf<div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-8"><label class="form-label" for="ubicacion_id">Ubicación a revisar</label><select class="form-select" id="ubicacion_id" name="ubicacion_id" required><option value="">Selecciona sala, bodega u otro espacio</option>@foreach($locations as $location)@php($label = str_ends_with(mb_strtoupper($location->codigo), '-'.mb_strtoupper($location->nombre)) ? ucfirst($location->tipo).' '.$location->nombre : $location->codigo.' — '.$location->nombre)<option value="{{ $location->id }}" @selected(old('ubicacion_id') == $location->id)>{{ $label }}@if($location->edificio || $location->piso) · {{ collect([$location->edificio, $location->piso])->filter()->join(', ') }}@endif</option>@endforeach</select><div class="form-text">Las ubicaciones antiguas se muestran con un nombre simple; las nuevas incluyen código y nombre.</div>@error('ubicacion_id')<div class="text-danger small mt-1">{{ $message }}</div>@enderror</div><div class="col-md-4"><button class="btn btn-primary w-100"><i class="bi bi-play-circle me-1"></i>Iniciar revisión</button></div></div></div></form>

<div class="d-flex justify-content-between align-items-center mb-2"><h2 class="h5 mb-0">Revisiones recientes</h2><span class="small text-body-secondary">Puedes retomar revisiones en curso o resolver sus pendientes.</span></div><div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Ubicación</th><th>Inicio</th><th>Estado</th><th>Escaneados</th><th></th></tr></thead><tbody>@forelse($inventories as $inventory)@php($label = str_ends_with(mb_strtoupper($inventory->ubicacion_codigo), '-'.mb_strtoupper($inventory->ubicacion_nombre)) ? ucfirst($inventory->ubicacion_tipo).' '.$inventory->ubicacion_nombre : $inventory->ubicacion_codigo.' — '.$inventory->ubicacion_nombre)@php($state = ['en_curso' => ['warning', 'En curso'], 'pendiente' => ['danger', 'Con pendientes'], 'finalizado' => ['success', 'Finalizado']][$inventory->estado] ?? ['secondary', $inventory->estado])<tr><td><strong>{{ $label }}</strong><div class="small text-body-secondary">{{ collect([$inventory->ubicacion_edificio, $inventory->ubicacion_piso, ucfirst($inventory->ubicacion_tipo), $inventory->iniciado_por_nombre])->filter()->join(' · ') }}</div></td><td>{{ \Illuminate\Support\Carbon::parse($inventory->iniciado_at)->format('d-m-Y H:i') }}</td><td><span class="badge text-bg-{{ $state[0] }}">{{ $state[1] }}</span></td><td>{{ $inventory->escaneados }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('physical-inventories.show', $inventory->id) }}">{{ $inventory->estado === 'en_curso' ? 'Continuar' : ($inventory->estado === 'pendiente' ? 'Resolver' : 'Ver resultado') }}</a></td></tr>@empty<tr><td colspan="5" class="text-center text-body-secondary p-4">Aún no hay revisiones físicas registradas.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $inventories->links() }}</div>
@endsection
