@extends('layouts.app')
@section('title', 'Revisión física')
@section('content')
@php($locationLabel = str_ends_with(mb_strtoupper($inventory->ubicacion_codigo), '-'.mb_strtoupper($inventory->ubicacion_nombre)) ? ucfirst($inventory->ubicacion_tipo).' '.$inventory->ubicacion_nombre : $inventory->ubicacion_codigo.' — '.$inventory->ubicacion_nombre)
@php($state = ['en_curso' => ['warning', 'En curso'], 'pendiente' => ['danger', 'Con pendientes'], 'finalizado' => ['success', 'Finalizada']][$inventory->estado] ?? ['secondary', $inventory->estado])
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><a class="small text-decoration-none" href="{{ route('physical-inventories.index') }}"><i class="bi bi-arrow-left"></i> Volver a revisiones</a><h1 class="h3 mb-1 mt-2">{{ $locationLabel }}</h1><p class="text-body-secondary mb-0">{{ collect([$inventory->ubicacion_edificio, $inventory->ubicacion_piso, ucfirst($inventory->ubicacion_tipo)])->filter()->join(' · ') }}@if($inventory->ubicacion_edificio || $inventory->ubicacion_piso) · @endif Escanea activos encontrados físicamente. Esta revisión no modifica su ubicación registrada.</p></div><span class="badge fs-6 text-bg-{{ $state[0] }}">{{ $state[1] }}</span></div>

@if(in_array($inventory->estado, ['en_curso', 'pendiente'], true))
<form method="POST" action="{{ route('physical-inventories.scan', $inventory->id) }}" class="card mb-4">@csrf<div class="card-body"><label class="form-label" for="codigo">Escanear código</label><div class="input-group"><input class="form-control form-control-lg" id="codigo" name="codigo" inputmode="text" pattern="[A-Za-z0-9-]*" maxlength="40" autofocus required placeholder="Activo fijo, serie o código de barras"><button class="btn btn-primary"><i class="bi bi-upc-scan me-1"></i>Registrar lectura</button></div><div class="form-text">Reconoce los mismos códigos usados en Escanear: activo fijo, número de serie o código asociado.</div>@error('codigo')<div class="text-danger small mt-2">{{ $message }}</div>@enderror</div></form>
@endif

<div class="row g-3 mb-4"><div class="col-sm-4"><div class="card h-100"><div class="card-body"><span class="text-body-secondary small">Esperados en esta ubicación</span><div class="display-6">{{ $expected->count() }}</div></div></div></div><div class="col-sm-4"><div class="card h-100"><div class="card-body"><span class="text-body-secondary small">Códigos escaneados</span><div class="display-6">{{ $scans->count() }}</div></div></div></div><div class="col-sm-4"><div class="card h-100"><div class="card-body"><span class="text-body-secondary small">Pendientes de revisar</span><div class="display-6">{{ $pending->count() }}</div></div></div></div></div>

<div class="card mb-4"><div class="card-header"><strong>Lecturas registradas</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Activo</th><th>Código leído</th><th>Resultado</th><th>Ubicación o asignación actual</th>@if(in_array($inventory->estado, ['en_curso', 'pendiente'], true))<th class="text-end">Acción</th>@endif</tr></thead><tbody>@forelse($scans as $scan)<tr><td><strong>{{ $scan->activo_fijo }}</strong><div class="small text-body-secondary">{{ trim(($scan->marca ?: '').' '.($scan->modelo ?: '')) }}</div></td><td><code>{{ $scan->codigo_escaneado }}</code></td><td><span class="badge text-bg-{{ $scan->resultado === 'encontrado' ? 'success' : 'warning' }}">{{ ['encontrado' => 'Encontrado', 'ubicacion_distinta' => 'Ubicación distinta', 'sin_ubicacion' => 'Sin ubicación'] [$scan->resultado] }}</span></td><td>{{ $scan->ubicacion_actual_nombre ? $scan->ubicacion_actual_codigo.' — '.$scan->ubicacion_actual_nombre : ($scan->responsable_nombre ? 'Asignado a: '.$scan->responsable_nombre : 'Sin ubicación') }}</td>@if(in_array($inventory->estado, ['en_curso', 'pendiente'], true))<td class="text-end"><form method="POST" action="{{ route('physical-inventories.scans.destroy', [$inventory->id, $scan->activo_id]) }}" data-confirm-message="¿Quitar la lectura {{ $scan->codigo_escaneado }} del activo {{ $scan->activo_fijo }}? El activo podrá escanearse nuevamente.">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-x-circle me-1"></i>Quitar lectura</button></form></td>@endif</tr>@empty<tr><td colspan="{{ in_array($inventory->estado, ['en_curso', 'pendiente'], true) ? 5 : 4 }}" class="text-center text-body-secondary p-4">Aún no hay códigos escaneados.</td></tr>@endforelse</tbody></table></div></div>

<div class="card"><div class="card-header d-flex justify-content-between align-items-center"><strong>Pendientes de revisar</strong><span class="small text-body-secondary">Registrados aquí, pero aún no escaneados</span></div><div class="card-body">@forelse($pending as $asset)<span class="badge text-bg-light border text-dark me-1 mb-1">{{ $asset->activo_fijo }}@if($asset->numero_serie) · {{ $asset->numero_serie }}@endif</span>@empty<p class="text-success mb-0"><i class="bi bi-check-circle me-1"></i>Todos los activos registrados en esta ubicación fueron escaneados.</p>@endforelse</div></div>
@if(in_array($inventory->estado, ['en_curso', 'pendiente'], true))<form method="POST" action="{{ route('physical-inventories.complete', $inventory->id) }}" class="mt-4" data-confirm-message="¿Cerrar la revisión? Si faltan equipos, quedará en estado Con pendientes para resolverlos después.">@csrf<button class="btn btn-success"><i class="bi bi-check2-circle me-1"></i>{{ $inventory->estado === 'pendiente' ? 'Revisar pendientes y cerrar' : 'Cerrar revisión' }}</button></form>@endif
@endsection
