@extends('layouts.app')
@section('content')
<h1 class="h3">Registrar movimiento</h1>
@if($products->isEmpty() || $warehouses->isEmpty())
    <div class="alert alert-warning">
        @if($products->isEmpty())
            Primero registra al menos un producto.
        @endif
        @if($warehouses->isEmpty())
            Registra una sede y una ubicación de tipo bodega antes de publicar movimientos.
        @endif
    </div>
@endif
<form method="POST" class="card" action="{{ route('movements.store') }}"><div class="card-body">@csrf @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif<input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}"><div class="row g-3"><div class="col-md-4"><label class="form-label">Tipo</label><select name="tipo" class="form-select">@foreach(['entrada','salida','devolucion','traslado','ajuste','baja'] as $type)<option>{{ $type }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Producto</label><select name="producto_id" class="form-select" @disabled($products->isEmpty())>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->nombre }} ({{ $product->codigo_interno }})</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Cantidad</label><input class="form-control" type="number" min="1" name="cantidad" required></div><div class="col-md-6"><label class="form-label">Bodega origen</label><select class="form-select" name="origen_id"><option value="">No aplica</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->nombre }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Bodega destino</label><select class="form-select" name="destino_id"><option value="">No aplica</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->nombre }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Tipo receptor (salida)</label><select name="receptor_tipo" class="form-select"><option value="">No aplica</option><option value="funcionario">Funcionario</option><option value="sala">Sala</option><option value="unidad">Unidad</option><option value="consumo_tecnico">Consumo técnico</option></select></div><div class="col-md-6"><label class="form-label">Nombre receptor</label><input class="form-control" name="receptor_nombre"></div><div class="col-md-6"><label class="form-label">Correo receptor</label><input class="form-control" type="email" name="receptor_email"></div><div class="col-md-6"><label class="form-label">Departamento</label><input class="form-control" name="receptor_departamento"></div><div class="col-12"><label class="form-label">Motivo</label><textarea class="form-control" name="motivo" required></textarea></div><div class="col-12"><label class="form-label">Observación</label><textarea class="form-control" name="observacion"></textarea></div></div></div><div class="card-footer"><button class="btn btn-primary" @disabled($products->isEmpty() || $warehouses->isEmpty())>Publicar</button><a class="btn btn-link" href="{{ route('movements.index') }}">Cancelar</a></div></form>
@endsection
